#!/usr/bin/env python
# -*-coding:utf-8-*-

import base64
import hashlib
import hmac
import json
import os
import time
import re
import urllib.request
from subprocess import run, PIPE
import pywifi

class hrequests:
    def __init__(self,content='',url=''):
        self.content=content
        self.url=url
    def get(self,url,params=None):
        if type(params)==dict:
            params=urllib.parse.urlencode(params).encode('ascii')
        request = urllib.request.Request(url=url, data=params)
        response = urllib.request.urlopen(request)
        return hrequests(response.read(),response.geturl())

requests=hrequests()

def char_code_at(stri, index):
    return 0 if index >= len(stri) else ord(stri[index])


def xencode(msg: str, key):
    '''
    xEncode
    '''
    def s(a: str, b: bool):
        c = len(a)
        v = []
        for i in range(0, c, 4):
            v.append(char_code_at(a, i) | (char_code_at(a, i+1) << 8) |
                     (char_code_at(a, i+2) << 16) | (char_code_at(a, i+3) << 24))
        if b:
            v.append(c)
        return v

    def l(a, b):
        d = len(a)
        c = (d-1) << 2
        if b:
            m = a[d-1]
            if (m < c-3) or (m > c):
                return None
            c = m
        for i in range(0, d):
            a[i] = ''.join([chr(a[i] & 0xff), chr((a[i] >> 8) & 0xff), chr(
                (a[i] >> 16) & 0xff), chr((a[i] >> 24) & 0xff)])
        if b:
            return (''.join(a))[0:c]
        else:
            return ''.join(a)

    if msg == "":
        return ""
    v = s(msg, True)
    k = s(key, False)
    n = len(v) - 1
    z = v[n]
    y = v[0]
    c = 0x86014019 | 0x183639A0
    m = 0
    e = 0
    p = 0
    q = 6 + 52 // (n + 1)
    d = 0
    while 0 < q:
        q -= 1
        d = d + c & (0x8CE0D9BF | 0x731F2640)
        e = d >> 2 & 3
        for p in range(0, n):
            y = v[p+1]
            m = z >> 5 ^ y << 2
            m += (y >> 3 ^ z << 4) ^ (d ^ y)
            m += k[(p & 3) ^ e] ^ z
            z = v[p] = v[p] + m & (0xEFB8D130 | 0x10472ECF)
        y = v[0]
        m = z >> 5 ^ y << 2
        m += (y >> 3 ^ z << 4) ^ (d ^ y)
        m += k[(n & 3) ^ e] ^ z
        z = v[n] = v[n] + m & (0xBB390742 | 0x44C6F8BD)
    return l(v, False)


def get_json(url, data):
    '''Http GET, return json
    '''
    callback = "jsonp%s" % int(time.time()*1000)
    data["callback"] = callback

    response = requests.get(url, data)
    response_content = response.content.decode('utf-8')[len(callback)+1:-1]
    response_json = json.loads(response_content)
    return response_json


def srun_login(username, password=None, action='login'):
    '''srun login and logout

    Args:
        username: username
        passwprd: password
        action: 'login' or 'logout'

    Returns:
        a json object.
    '''
    def data_info(get_data, token):
        if get_data['action'] == 'login':
            x_encode_json = {
                "username": get_data['username'],
                "password": get_data['password'],
                "ip": get_data['ip'],
                "acid": get_data['ac_id'],
                "enc_ver": enc
            }
        else:
            x_encode_json = {
                "username": get_data['username'],
                "ip": get_data['ip'],
                "acid": get_data['ac_id'],
                "enc_ver": enc
            }

        x_encode_str = json.dumps(x_encode_json, separators=(',', ':'))
        x_encode_key = token
        x_encode_res = xencode(x_encode_str, x_encode_key)

        # base64_encode
        mapping = dict(zip("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
                           "LVoJPiCN2R8G90yg+hmFHuacZ1OWMnrsSTXkYpUq/3dlbfKwv6xztjI7DeBE45QA="))
        b64_res = base64.b64encode(
            bytes([ord(s) for s in x_encode_res])).decode()
        base64_encode_res = ''.join([mapping[b] for b in b64_res])
        return "{SRBX1}" + base64_encode_res

    def pwd_hmd5(password, token):
        hmac_key = token.encode('utf-8')
        hmac_msg = password.encode('utf-8')
        hmd5 = hmac.new(hmac_key, hmac_msg, digestmod='MD5').hexdigest()
        return '{MD5}' + hmd5

    def checksum(get_data, token):
        if get_data['action'] == 'login':
            str_list = ['', get_data['username'], get_data['password'][5:],
                        get_data['ac_id'], get_data['ip'], str(n), str(type_), get_data['info']]
        else:
            str_list = ['', get_data['username'], get_data['ac_id'],
                        get_data['ip'], str(n), str(type_), get_data['info']]
        chksum_str = token.join(str_list)
        chksum = hashlib.sha1(chksum_str.encode('utf-8')).hexdigest()
        return chksum

    enc = "srun_bx1"
    n = 200
    type_ = 1
    get_challenge_url = "https://beiradius.chd.edu.cn/cgi-bin/get_challenge"
    srun_portal_url = "https://beiradius.chd.edu.cn/cgi-bin/srun_portal"
    url = 'https://beiradius.chd.edu.cn'
    r = requests.get(url)
    ac_id=re.findall(r'index_(\d*).html',r.url)[0]
    if action == 'login':
        get_data = {
            "action": action,
            "username": username,
            "password": password,
            "ac_id": ac_id,
            "ip": '',
            "info": '',
            "chksum": '',
            "n": n,
            "type": type_
        }
    else:
        get_data = {
            "action": action,
            "username": username,
            # "password": password, # logout,
            "ac_id": ac_id,
            "ip": '',
            "info": '',
            "chksum": '',
            "n": n,
            "type": type_
        }

    # get token
    challenge_json = get_json(
        get_challenge_url, {"username": get_data['username']})
    token = challenge_json['challenge']
    get_data['ip'] = challenge_json['client_ip']
    get_data['info'] = data_info(get_data, token)
    if action == 'login':
        get_data['password'] = pwd_hmd5('', token)
    get_data['chksum'] = checksum(get_data, token)
    res = get_json(srun_portal_url, get_data)
    return res

def wifi_name():
    wifi = pywifi.PyWiFi()
    ifaces = wifi.interfaces()[0]
    profile = ifaces.scan_results()[0]
    name=profile.ssid
    return name

while True:
    time.sleep(2)
    if wifi_name()=='CHD-WiFi':
        r = run('ping www.baidu.com',
                stdout=PIPE,
                stderr=PIPE,
                stdin=PIPE,
                shell=True)
        if r.returncode:
            if __name__ == "__main__":
                username = "username"#改成学号，移动加@cmcc,电信加@chinanet
                password = "password"
                srun_login(username, password)
